### ISSUE TITLE
login on staging only works on every 2nd attempt

### ISSUE THREAD

**Issue by lieblingswelt** [pixelated-project/pixelated-dispatcher#101] opened 2015-05-19 08:54 UTC
# behaviour observed
Every second time I login as behave testuser via the webinterface on staging, I get a service currently unavailable error and cannot log in.

# how to reproduce
go to staging environment port 8080
login as behave-testuser
->you should be able to login
logout
login again as behave-testuser
->you should see a service currently not available notice

on the docker logs for behave-testuser, I am seing the following stacktrace on error:
```
2015-05-19 08:13:53+0000 [HTTPChannel,0,172.17.42.1] 172.17.42.1 - - [19/May/2015:08:13:52 +0000] "GET /mails?q=tag%3A%22inbox%22&p=1&w=25 HTTP/1.1" 200 2488 "https://staging.pixelated-project.org:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36"
2015-05-19 08:13:53+0000 [-] 172.17.42.1 - - [19/May/2015:08:13:52 +0000] "GET /tags HTTP/1.1" 200 409 "https://staging.pixelated-project.org:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36"
2015-05-19 08:14:07+0000 [-] Received SIGTERM, shutting down.
2015-05-19 08:14:07+0000 [leap.mail.smtp.gateway.SMTPFactory] (TCP Port 4650 Closed)
2015-05-19 08:14:07+0000 [leap.mail.smtp.gateway.SMTPFactory] Stopping factory <leap.mail.smtp.gateway.SMTPFactory instance at 0x7f4e5c2963b0>
2015-05-19 08:14:07+0000 [twisted.web.server.Site] (TCP Port 4567 Closed)
2015-05-19 08:14:07+0000 [twisted.web.server.Site] Stopping factory <twisted.web.server.Site instance at 0x7f4e61838518>
2015-05-19 08:14:07+0000 [-] Main loop terminated.
2015-05-19 08:49:12+0000 [-] Log opened.
2015-05-19 08:49:12+0000 [-] Site starting on 4567
2015-05-19 08:49:12+0000 [-] Starting factory <twisted.web.server.Site instance at 0x7f261258bab8>
2015-05-19 08:49:22+0000 [-] SMTPFactory starting on 4650
2015-05-19 08:49:22+0000 [-] Starting factory <leap.mail.smtp.gateway.SMTPFactory instance at 0x7f2617bd0518>
```

# expected behaviour:
Every time I log in, I want to be connected to my instance.

**Comment by bwagnerr** [comment] 2015-07-24 19:29
We have been using the environments somewhat heavily recently and I've not come across this, I confirmed with others too.

I'll close this as fixed/cannot reproduce

**Closed by bwagnerr** 2015-07-24 19:29 UTC
Labels: bug
